vscode:
  extensions:
    - octref.vetur@0.22.3:Mwv282XMv00pVVOQeZ6Ngg==
    
    - formulahendry.auto-rename-tag@0.1.0:/DaYBGQJ0OJXTfLl4zwBLA==

    - hollowtree.vue-snippets@0.1.11:6Eh/noAzUlIM2G8pAmdZqA==

    - HookyQR.beautify@1.5.0:mXo/OcopUVNHHxCPZWwlxQ==

    - esbenp.prettier-vscode@2.3.0:1F0Pvb/ORZ/T+b60LIMs8w==

tasks:
  - command: "npm install"